version: '3'
services:
    mysql:
        build:
            context: ./
            dockerfile: MySQLDockerfile
        container_name: mysql
        volumes:
            - ./my.cnf:/etc/mysql/my.cnf
        ports:
            - "3306:3306"
        command: ["mysqld","--default-authentication-plugin=mysql_native_password"]
        restart: always
    app:
        build:
            context: ./
            dockerfile: JavaDockerfile
        container_name: sca-app
        ports:
            - "8080:8080"
        depends_on:
            - mysql
            - nginx 
        restart: always
    nginx:
        image:  nginx
        restart: always
        volumes:
            - F:\anjing\workspace\codingnet\codeChecker-ui:/usr/share/nginx/html:ro
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
        
        